# Imports

In [1]:
import face_utilities as face
import os

PHASE 1 - Parse the face dataset

In [2]:
print("Parsing Face Dataset STARTED...")
face_images = face.parse_face_dataset()
print("Parsing Face Dataset COMPLETE!")

Parsing Face Dataset STARTED...
Total Face Images Found: 558
Parsing Face Dataset COMPLETE!


PHASE 2 - Perform face detection

In [3]:
print("Face Image Preprocessing STARTED...")
# Suppress display for face detection
face.face_detection(face_images, display = False)
print("Face Image Preprocessing COMPLETE!")

Face Image Preprocessing STARTED...
Face Image Preprocessing COMPLETE!


PHASE 3 - Perform facial feature extraction

In [4]:
print("Face Feature Extraction STARTED...")
# Input directory containing images with detected faces
input_directory_detection = 'Face_Output/Face_Output_Detection'
# Output directory for saving images with landmarks and detected faces
output_directory_feature_extraction = 'Face_Output'
features, labels = face.facial_feature_extraction(
    input_directory_detection, output_directory_feature_extraction)
print("Face Feature Extraction COMPLETE!")

Face Feature Extraction STARTED...
Face Feature Extraction COMPLETE!


PHASE 4 - Extract facial landmarks from an image


In [5]:
print("Extracting facial landmarks STARTED...")
# Input directory containing images with extracted facial features
input_directory_extraction = 'Face_Output/Face_Output_Feature_Extraction'
# Output directory for saving images with facial landmarks
output_directory_landmarks = 'Face_Output'
face.extract_facial_landmarks(
    input_directory_extraction, output_directory_landmarks)
print("Extracting facial landmarks COMPLETE!")

Extracting facial landmarks STARTED...
Extracting facial landmarks COMPLETE!


PHASE 5 - Convert facial landmarks into feature vectors


In [6]:
print("Converting facial landmarks to feature vectors STARTED...")

# Assuming you have extracted landmarks and stored them in 'features'
# and you want to save the feature vectors in 'output_dir'
output_dir = 'Face_Output/Face_Output_LFCV'
face.landmarks_to_features(features, output_dir=output_dir)

print("Converting facial landmarks to feature vectors COMPLETE!")

# View the stored feature vectors
stored_feature_vectors = []

# Iterate over files in the output directory
for filename in os.listdir(output_dir):
    if filename.endswith('.npy'):  # Check if the file is a NumPy binary file
        # Construct the file path
        filepath = os.path.join(output_dir, filename)
        # Load the data from the file
        feature_vector = face.np.load(filepath)
        # Append the feature vector to the list
        stored_feature_vectors.append(feature_vector)
        # Print the contents of the feature vector
        print("Feature vector from file:", filename)
        print(feature_vector)

# Print the number of stored feature vectors
print("Number of feature vectors generated:", len(stored_feature_vectors))

Converting facial landmarks to feature vectors STARTED...
Converting facial landmarks to feature vectors COMPLETE!
Feature vector from file: landmarks_0.npy
[49 18 15 31  9 31  9]
Feature vector from file: landmarks_1.npy
[64 23 19 41 13 41 13]
Feature vector from file: landmarks_10.npy
[63 22 23 36 11 36 11]
Feature vector from file: landmarks_100.npy
[64 21 20 36 12 36 12]
Feature vector from file: landmarks_101.npy
[33 13  7 24  9 24  9]
Feature vector from file: landmarks_102.npy
[42 15  8 30 11 30 11]
Feature vector from file: landmarks_103.npy
[93 35 25 70 12 70 12]
Feature vector from file: landmarks_104.npy
[92 30 25 48 16 48 16]
Feature vector from file: landmarks_105.npy
[70 25 11 43 10 43 10]
Feature vector from file: landmarks_106.npy
[82 28 21 47 13 47 13]
Feature vector from file: landmarks_107.npy
[70 22 19 35 13 35 13]
Feature vector from file: landmarks_108.npy
[69 22 18 37 12 37 12]
Feature vector from file: landmarks_109.npy
[61 20 17 33 11 33 11]
Feature vector from

PHASE 6 - Splitting Data (80% Training, 20% Test)


In [7]:
# Define directory paths
train_dir = 'Face_Output/Face_Output_Split_Train'
test_dir = 'Face_Output/Face_Output_Split_Test'

# Split the data
face.split_data(features, labels, train_dir, test_dir)

Training set size: 264
Testing set size: 66

Training Data:
Filename: X_train.npy, Shape: (264, 7)
Filename: y_train.npy, Shape: (264,)

Testing Data:
Filename: X_test.npy, Shape: (66, 7)
Filename: y_test.npy, Shape: (66,)
